name: unzip

on:
  workflow_dispatch:

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Unzip g.zip
      run: |
        unzip -o g.zip
        rm g.zip

    - name: Commit unzipped files
      run: |
        git config --global user.email "bot@example.com"
        git config --global user.name "GitHub Bot"
        git add .
        git commit -m "Unzipped g.zip"
        git push
